// viking placeholder
// viking v1
// drone v1
let playerAssets = [img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . d d . . . . . . . 
    . . . . . . d 1 1 d . . . . . . 
    . . . . . . c d d c . . . . . . 
    . . . c c . c b b c . c c . . . 
    c c f e e f c b b c f e e f c c 
    c b f f f f b b b b f f f f b c 
    c b b b b b b b b b b b b b b c 
    . c f f f f b b b b f f f f c . 
    . . c b b f b b b b f b b c . . 
    . . c b c . c b b c . c b c . . 
    . . . c . . c b b c . . c . . . 
    . . . . . . . c c . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, img`
    .............7....7.............
    .............77..77.............
    .............7b..b7.............
    .............7bbbb7.............
    ............7bbcebb7............
    ............7bbecbb7............
    .......cc...7bbccbb7...cc.......
    .......cc...cbcbbcbc...cc.......
    .777777cc77cbbcbbcbbc77cc777777.
    ddddcbbbbdcdbcbddbcbdcdbbbbcdddd
    bbbbcbbbbdcdbcbddbcbdcdbbbbcbbbb
    bbbbbcbbbdcdbcbccbcbdcdbbbcbbbbb
    .bbbbcbbbdecccb77bcccedbbbcbbbb.
    ..bbbcbbbeccccb77bccccebbbcbbb..
    ...bbbcbbccbddb77bddbccbbcbbb...
    ....bbcbbcbbbdccccdbbbcbbcbb....
    .....bcbbcbbbde44edbbbcbbcb.....
    ......cbbcbbbd4bb4dbbbcbbc......
    .......cc.cccccccccccc.cc.......
    .......c...ccce44eccc...c.......
    ...........6e84dd48e6...........
    ............48....84............
    `, img`
    ....................
    .........cc.........
    .......76cc67.......
    .....77bbccbb77.....
    ....7bbcceeccbb7....
    ...7bbc......cbb7...
    ...7bc.bbccbb.cb7...
    ..7bc.bccf4ccb.cb7..
    ..6bc.bcffffcb.cb6..
    .ccc.bc4f45ffcb.ccc.
    .ccc.bcff54f4cb.ccc.
    ..6bc.bcffffcb.cb6..
    ..7bc.bcc4fccb.cb7..
    ...7bc.bbccbb.cb7...
    ...7bbc..bb..cbb7...
    ....7bbcc..ccbb7....
    .....77bbccbb77.....
    .......76cc67.......
    .........cc.........
    ....................
    `]
let supportAssets = 0
let combatAssets = 0
let gameUIAssets = 0
let protossAssets = 0
let zergAssets = 0
let terranAssets = 0
